### ISSUE TITLE
Comma missing in the config file

### ISSUE THREAD

**Issue by raduchiriac** [PacktPublishing/Webpack-5-Up-and-Running#1]
https://github.com/PacktPublishing/Webpack-5-Up-and-Running/blob/2435ef2576d1a610229bddc9c4d951afec601891/Chapter%2002/Dynamic%20Imports/webpack.config.js#L5

Shouldn't it be: `another: "./src/another-module.js"` instead of twice the index?

**Comment by shubham763** [comment]
Hi @raduchiriac,
Yes, it should be "another: './src/another-module.js',". The changes have been made. Thank you!
